<?php

namespace AppBundle\Repository;

use AppBundle\ValueObject\EmployeeFilter;
use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
    /**
     * @param EmployeeFilter $employeeFilter
     * @return array
     */
    public function findByEmployeeFilter($employeeFilter)
    {
        $qb = $this->createQueryBuilder('employee')
            ->select('employee')
            ->orderBy('employee.lastName')
            ->addOrderBy('employee.firstName')
            ->addOrderBy('employee.patronymic');

        if (strlen($employeeFilter->getDepartmentName()) > 0) {
            $qb->leftJoin('employee.department', 'department')
                ->where('department.name LIKE :filterDepartmentName')
                ->setParameter('filterDepartmentName', '%' . $employeeFilter->getDepartmentName() . '%');
        }

        if (!is_null($employeeFilter->getHireDate())) {
            $qb->andWhere('employee.hireDate > :filterHireDate')
                ->setParameter('filterHireDate', $employeeFilter->getHireDate()->format('Y-m-d'));
        }

        if (!is_null($employeeFilter->getRetireDate())) {
            $qb->andWhere('employee.retireDate < :filterRetireDate')
                ->setParameter('filterRetireDate', $employeeFilter->getRetireDate()->format('Y-m-d'));
        }

        return $qb->getQuery()->getResult();
    }
}
